plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
just_the_docs:
  color_scheme: dark
include:
 - README.md
 - exercises/basic/exercise1/README.md
 - exercises/basic/exercise1/README.md
 - exercises/basic/exercise3/README.md
 - exercises/artemis/exercise1/README.md
 - exercises/artemis/exercise2/README.md
 - exercises/artemis/exercise3/README.md
 - exercises/Software/exercise1/README.md
