remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true


color_scheme: dark
color_scheme_toggle: true

baseurl: "/Workshops"

navigation:
  data_file: navigation.yml

include:
 - README.md
 - exercises/basic/exercise1/README.md
 - exercises/basic/exercise1/README.md
 - exercises/basic/exercise3/README.md
 - exercises/artemis/exercise1/README.md
 - exercises/artemis/exercise2/README.md
 - exercises/artemis/exercise3/README.md
 - exercises/Software/exercise1/README.md
