remote_theme: just-the-docs/just-the-docs

markdown: GFM

plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true


color_scheme: dark
color_scheme_toggle: true

baseurl: "/Workshops"

navigation:
  data_file: navigation.yml

include:
 - README.md
 - exercises/basic/Exercise1/README.md
 - exercises/basic/Exercise2/README.md
 - exercises/basic/Exercise3/README.md
 - exercises/artemis/Exercise1/README.md
 - exercises/artemis/Exercise2/README.md
 - exercises/artemis/Exercise3/README.md
 - exercises/Software/Exercise1/README.md
 - exercises/gpu/README.md
 - exercises/gpu/Exercise1/README.md
 - exercises/gpu/Exercise2/README.md
 - exercises/gpu/Exercise3/README.md
 - exercises/gpu/Exercise4/README.md
 - solutions/basic/Exercise1/README.md
 - solutions/basic/Exercise2/README.md
 - solutions/basic/Exercise3/README.md
 - solutions/gpu/README.md


