#!/bin/bash
#SBATCH --job-name=Workshop_Basic
#SBATCH --partition=Workshop     
#SBATCH --cpus-per-task=1        
#SBATCH --mem=2G                 # total memory per node
#SBATCH --output=output.%j.out   # output file with job ID
#SBATCH --error=output.%j.err    # error file (can be merged with output if you want)

echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
echo $SLURMD_NODENAME
echo $SLURM_SUBMIT_DIR
